---

- name: Repository Key for influxdata
  apt_key:
    keyserver: keys.gnupg.net
    id: 418A7F2FB0E1E6E7EABF6FE8C2E73424D59097AB
    state: present

- name: Repository sources for influxdata
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian jessie stable"
    state: present

